### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by versae** [Princeton-CDH/piffle#6]
Great little library, exactly what I need!

I've seen that Python 3 is supported in the [`develop`](https://github.com/emory-lits-labs/piffle/tree/develop) branch. Any plans on updating the package in PyPI?

Thanks.

**Comment by rlskoeser** [comment]
Seconded.  @jayvarner could you make a new release and publish on pypi?  It would be helpful for me as well.  I've been installing from my fork on GitHub, but it would be much nicer to use an actual release.

**Comment by rlskoeser** [comment]
@versae I got permission from Emory to take over maintenance.  I'll try to get a new release published soon.

**Comment by versae** [comment]
Great news! Thanks.
